// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const buildDatabaseUrl = (): string | undefined => {
  const host = process.env["DB_HOST"];
  const port = process.env["DB_PORT"];
  const database = process.env["DB_NAME"];
  const user = process.env["DB_USER"];
  const password = process.env["DB_PASSWORD"];

  if (!host || !port || !database || !user || !password) {
    return process.env["DATABASE_URL"];
  }

  return `postgresql://${encodeURIComponent(user)}:${encodeURIComponent(password)}@${host}:${port}/${database}?schema=public`;
};

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: buildDatabaseUrl(),
  },
});
