export const dataBaseSchema = {
  schema: "public",
  tables: [
    {
      table: "brands",
      columns: [
        {
          udt: "uuid",
          name: "id",
          default: null,
          dataType: "uuid",
          nullable: false,
          position: 1,
          maxLength: null,
          numericScale: null,
          numericPrecision: null,
        },
        {
          udt: "varchar",
          name: "name",
          default: null,
          dataType: "character varying",
          nullable: false,
          position: 2,
          maxLength: 255,
          numericScale: null,
          numericPrecision: null,
        },
        {
          udt: "timestamptz",
          name: "created_at",
          default: null,
          dataType: "timestamp with time zone",
          nullable: false,
          position: 3,
          maxLength: null,
          numericScale: null,
          numericPrecision: null,
        },
        {
          udt: "timestamptz",
          name: "updated_at",
          default: null,
          dataType: "timestamp with time zone",
          nullable: false,
          position: 4,
          maxLength: null,
          numericScale: null,
          numericPrecision: null,
        },
      ],
      indexes: [
        {
          name: "brands_name_key",
          definition:
            "CREATE UNIQUE INDEX brands_name_key ON public.brands USING btree (name)",
        },
        {
          name: "brands_name_key1",
          definition:
            "CREATE UNIQUE INDEX brands_name_key1 ON public.brands USING btree (name)",
        },
        {
          name: "brands_pkey",
          definition:
            "CREATE UNIQUE INDEX brands_pkey ON public.brands USING btree (id)",
        },
      ],
      constraints: [
        {
          name: "2200_16385_1_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "2200_16385_2_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "2200_16385_3_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "2200_16385_4_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "brands_name_key",
          type: "UNIQUE",
          column: "name",
          referencesTable: "brands",
          referencesColumn: "name",
        },
        {
          name: "brands_name_key1",
          type: "UNIQUE",
          column: "name",
          referencesTable: "brands",
          referencesColumn: "name",
        },
        {
          name: "brands_pkey",
          type: "PRIMARY KEY",
          column: "id",
          referencesTable: "brands",
          referencesColumn: "id",
        },
      ],
    },
    {
      table: "cat_req_measurements",
      columns: [
        {
          udt: "uuid",
          name: "id",
          default: null,
          dataType: "uuid",
          nullable: false,
          position: 1,
          maxLength: null,
          numericScale: null,
          numericPrecision: null,
        },
        {
          udt: "uuid",
          name: "sub_category_id",
          default: null,
          dataType: "uuid",
          nullable: false,
          position: 2,
          maxLength: null,
          numericScale: null,
          numericPrecision: null,
        },
        {
          udt: "uuid",
          name: "measurement_type_id",
          default: null,
          dataType: "uuid",
          nullable: false,
          position: 3,
          maxLength: null,
          numericScale: null,
          numericPrecision: null,
        },
        {
          udt: "timestamptz",
          name: "created_at",
          default: null,
          dataType: "timestamp with time zone",
          nullable: false,
          position: 4,
          maxLength: null,
          numericScale: null,
          numericPrecision: null,
        },
        {
          udt: "timestamptz",
          name: "updated_at",
          default: null,
          dataType: "timestamp with time zone",
          nullable: false,
          position: 5,
          maxLength: null,
          numericScale: null,
          numericPrecision: null,
        },
      ],
      indexes: [
        {
          name: "cat_req_measurements_pkey",
          definition:
            "CREATE UNIQUE INDEX cat_req_measurements_pkey ON public.cat_req_measurements USING btree (id)",
        },
      ],
      constraints: [
        {
          name: "2200_16468_1_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "2200_16468_2_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "2200_16468_3_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "2200_16468_4_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "2200_16468_5_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "cat_req_measurements_measurement_type_id_fkey",
          type: "FOREIGN KEY",
          column: "measurement_type_id",
          referencesTable: "measurement_types",
          referencesColumn: "id",
        },
        {
          name: "cat_req_measurements_pkey",
          type: "PRIMARY KEY",
          column: "id",
          referencesTable: "cat_req_measurements",
          referencesColumn: "id",
        },
        {
          name: "cat_req_measurements_sub_category_id_fkey",
          type: "FOREIGN KEY",
          column: "sub_category_id",
          referencesTable: "sub_categories",
          referencesColumn: "id",
        },
      ],
    },
    {
      table: "categories",
      columns: [
        {
          udt: "uuid",
          name: "id",
          default: null,
          dataType: "uuid",
          nullable: false,
          position: 1,
          maxLength: null,
          numericScale: null,
          numericPrecision: null,
        },
        {
          udt: "varchar",
          name: "name",
          default: null,
          dataType: "character varying",
          nullable: false,
          position: 2,
          maxLength: 255,
          numericScale: null,
          numericPrecision: null,
        },
        {
          udt: "timestamptz",
          name: "created_at",
          default: null,
          dataType: "timestamp with time zone",
          nullable: false,
          position: 3,
          maxLength: null,
          numericScale: null,
          numericPrecision: null,
        },
        {
          udt: "timestamptz",
          name: "updated_at",
          default: null,
          dataType: "timestamp with time zone",
          nullable: false,
          position: 4,
          maxLength: null,
          numericScale: null,
          numericPrecision: null,
        },
      ],
      indexes: [
        {
          name: "categories_name_key",
          definition:
            "CREATE UNIQUE INDEX categories_name_key ON public.categories USING btree (name)",
        },
        {
          name: "categories_name_key1",
          definition:
            "CREATE UNIQUE INDEX categories_name_key1 ON public.categories USING btree (name)",
        },
        {
          name: "categories_pkey",
          definition:
            "CREATE UNIQUE INDEX categories_pkey ON public.categories USING btree (id)",
        },
      ],
      constraints: [
        {
          name: "2200_16392_1_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "2200_16392_2_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "2200_16392_3_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "2200_16392_4_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "categories_name_key",
          type: "UNIQUE",
          column: "name",
          referencesTable: "categories",
          referencesColumn: "name",
        },
        {
          name: "categories_name_key1",
          type: "UNIQUE",
          column: "name",
          referencesTable: "categories",
          referencesColumn: "name",
        },
        {
          name: "categories_pkey",
          type: "PRIMARY KEY",
          column: "id",
          referencesTable: "categories",
          referencesColumn: "id",
        },
      ],
    },
    {
      table: "horse_measurements",
      columns: [
        {
          udt: "uuid",
          name: "id",
          default: null,
          dataType: "uuid",
          nullable: false,
          position: 1,
          maxLength: null,
          numericScale: null,
          numericPrecision: null,
        },
        {
          udt: "uuid",
          name: "horse_id",
          default: null,
          dataType: "uuid",
          nullable: false,
          position: 2,
          maxLength: null,
          numericScale: null,
          numericPrecision: null,
        },
        {
          udt: "uuid",
          name: "measurement_type_id",
          default: null,
          dataType: "uuid",
          nullable: false,
          position: 3,
          maxLength: null,
          numericScale: null,
          numericPrecision: null,
        },
        {
          udt: "numeric",
          name: "value",
          default: null,
          dataType: "numeric",
          nullable: false,
          position: 4,
          maxLength: null,
          numericScale: 2,
          numericPrecision: 5,
        },
        {
          udt: "timestamptz",
          name: "measurement_date",
          default: null,
          dataType: "timestamp with time zone",
          nullable: false,
          position: 5,
          maxLength: null,
          numericScale: null,
          numericPrecision: null,
        },
        {
          udt: "timestamptz",
          name: "created_at",
          default: null,
          dataType: "timestamp with time zone",
          nullable: false,
          position: 6,
          maxLength: null,
          numericScale: null,
          numericPrecision: null,
        },
        {
          udt: "timestamptz",
          name: "updated_at",
          default: null,
          dataType: "timestamp with time zone",
          nullable: false,
          position: 7,
          maxLength: null,
          numericScale: null,
          numericPrecision: null,
        },
      ],
      indexes: [
        {
          name: "horse_measurements_pkey",
          definition:
            "CREATE UNIQUE INDEX horse_measurements_pkey ON public.horse_measurements USING btree (id)",
        },
      ],
      constraints: [
        {
          name: "2200_16483_1_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "2200_16483_2_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "2200_16483_3_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "2200_16483_4_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "2200_16483_5_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "2200_16483_6_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "2200_16483_7_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "horse_measurements_horse_id_fkey",
          type: "FOREIGN KEY",
          column: "horse_id",
          referencesTable: "horses",
          referencesColumn: "id",
        },
        {
          name: "horse_measurements_measurement_type_id_fkey",
          type: "FOREIGN KEY",
          column: "measurement_type_id",
          referencesTable: "measurement_types",
          referencesColumn: "id",
        },
        {
          name: "horse_measurements_pkey",
          type: "PRIMARY KEY",
          column: "id",
          referencesTable: "horse_measurements",
          referencesColumn: "id",
        },
      ],
    },
    {
      table: "horses",
      columns: [
        {
          udt: "uuid",
          name: "id",
          default: null,
          dataType: "uuid",
          nullable: false,
          position: 1,
          maxLength: null,
          numericScale: null,
          numericPrecision: null,
        },
        {
          udt: "varchar",
          name: "name",
          default: null,
          dataType: "character varying",
          nullable: false,
          position: 2,
          maxLength: 255,
          numericScale: null,
          numericPrecision: null,
        },
        {
          udt: "uuid",
          name: "rider_id",
          default: null,
          dataType: "uuid",
          nullable: false,
          position: 3,
          maxLength: null,
          numericScale: null,
          numericPrecision: null,
        },
        {
          udt: "timestamptz",
          name: "created_at",
          default: null,
          dataType: "timestamp with time zone",
          nullable: false,
          position: 4,
          maxLength: null,
          numericScale: null,
          numericPrecision: null,
        },
        {
          udt: "timestamptz",
          name: "updated_at",
          default: null,
          dataType: "timestamp with time zone",
          nullable: false,
          position: 5,
          maxLength: null,
          numericScale: null,
          numericPrecision: null,
        },
      ],
      indexes: [
        {
          name: "horses_pkey",
          definition:
            "CREATE UNIQUE INDEX horses_pkey ON public.horses USING btree (id)",
        },
      ],
      constraints: [
        {
          name: "2200_16458_1_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "2200_16458_2_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "2200_16458_3_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "2200_16458_4_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "2200_16458_5_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "horses_pkey",
          type: "PRIMARY KEY",
          column: "id",
          referencesTable: "horses",
          referencesColumn: "id",
        },
        {
          name: "horses_rider_id_fkey",
          type: "FOREIGN KEY",
          column: "rider_id",
          referencesTable: "riders",
          referencesColumn: "id",
        },
      ],
    },
    {
      table: "measurement_types",
      columns: [
        {
          udt: "uuid",
          name: "id",
          default: null,
          dataType: "uuid",
          nullable: false,
          position: 1,
          maxLength: null,
          numericScale: null,
          numericPrecision: null,
        },
        {
          udt: "varchar",
          name: "code",
          default: null,
          dataType: "character varying",
          nullable: false,
          position: 2,
          maxLength: 255,
          numericScale: null,
          numericPrecision: null,
        },
        {
          udt: "varchar",
          name: "unit",
          default: null,
          dataType: "character varying",
          nullable: false,
          position: 3,
          maxLength: 255,
          numericScale: null,
          numericPrecision: null,
        },
        {
          udt: "enum_measurement_types_applies_to",
          name: "applies_to",
          default: null,
          dataType: "USER-DEFINED",
          nullable: false,
          position: 4,
          maxLength: null,
          numericScale: null,
          numericPrecision: null,
        },
        {
          udt: "text",
          name: "description",
          default: null,
          dataType: "text",
          nullable: true,
          position: 5,
          maxLength: null,
          numericScale: null,
          numericPrecision: null,
        },
        {
          udt: "timestamptz",
          name: "created_at",
          default: null,
          dataType: "timestamp with time zone",
          nullable: false,
          position: 6,
          maxLength: null,
          numericScale: null,
          numericPrecision: null,
        },
        {
          udt: "timestamptz",
          name: "updated_at",
          default: null,
          dataType: "timestamp with time zone",
          nullable: false,
          position: 7,
          maxLength: null,
          numericScale: null,
          numericPrecision: null,
        },
      ],
      indexes: [
        {
          name: "measurement_types_code_key",
          definition:
            "CREATE UNIQUE INDEX measurement_types_code_key ON public.measurement_types USING btree (code)",
        },
        {
          name: "measurement_types_code_key1",
          definition:
            "CREATE UNIQUE INDEX measurement_types_code_key1 ON public.measurement_types USING btree (code)",
        },
        {
          name: "measurement_types_pkey",
          definition:
            "CREATE UNIQUE INDEX measurement_types_pkey ON public.measurement_types USING btree (id)",
        },
      ],
      constraints: [
        {
          name: "2200_16417_1_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "2200_16417_2_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "2200_16417_3_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "2200_16417_4_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "2200_16417_6_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "2200_16417_7_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "measurement_types_code_key",
          type: "UNIQUE",
          column: "code",
          referencesTable: "measurement_types",
          referencesColumn: "code",
        },
        {
          name: "measurement_types_code_key1",
          type: "UNIQUE",
          column: "code",
          referencesTable: "measurement_types",
          referencesColumn: "code",
        },
        {
          name: "measurement_types_pkey",
          type: "PRIMARY KEY",
          column: "id",
          referencesTable: "measurement_types",
          referencesColumn: "id",
        },
      ],
    },
    {
      table: "product_size_ranges",
      columns: [
        {
          udt: "uuid",
          name: "id",
          default: null,
          dataType: "uuid",
          nullable: false,
          position: 1,
          maxLength: null,
          numericScale: null,
          numericPrecision: null,
        },
        {
          udt: "uuid",
          name: "product_id",
          default: null,
          dataType: "uuid",
          nullable: false,
          position: 2,
          maxLength: null,
          numericScale: null,
          numericPrecision: null,
        },
        {
          udt: "uuid",
          name: "measurement_type_id",
          default: null,
          dataType: "uuid",
          nullable: false,
          position: 3,
          maxLength: null,
          numericScale: null,
          numericPrecision: null,
        },
        {
          udt: "varchar",
          name: "size_label",
          default: null,
          dataType: "character varying",
          nullable: false,
          position: 4,
          maxLength: 255,
          numericScale: null,
          numericPrecision: null,
        },
        {
          udt: "float8",
          name: "min_value",
          default: null,
          dataType: "double precision",
          nullable: false,
          position: 5,
          maxLength: null,
          numericScale: null,
          numericPrecision: 53,
        },
        {
          udt: "float8",
          name: "max_value",
          default: null,
          dataType: "double precision",
          nullable: false,
          position: 6,
          maxLength: null,
          numericScale: null,
          numericPrecision: 53,
        },
        {
          udt: "timestamptz",
          name: "created_at",
          default: null,
          dataType: "timestamp with time zone",
          nullable: false,
          position: 7,
          maxLength: null,
          numericScale: null,
          numericPrecision: null,
        },
        {
          udt: "timestamptz",
          name: "updated_at",
          default: null,
          dataType: "timestamp with time zone",
          nullable: false,
          position: 8,
          maxLength: null,
          numericScale: null,
          numericPrecision: null,
        },
      ],
      indexes: [
        {
          name: "product_size_ranges_pkey",
          definition:
            "CREATE UNIQUE INDEX product_size_ranges_pkey ON public.product_size_ranges USING btree (id)",
        },
      ],
      constraints: [
        {
          name: "2200_16498_1_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "2200_16498_2_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "2200_16498_3_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "2200_16498_4_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "2200_16498_5_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "2200_16498_6_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "2200_16498_7_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "2200_16498_8_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "product_size_ranges_measurement_type_id_fkey",
          type: "FOREIGN KEY",
          column: "measurement_type_id",
          referencesTable: "measurement_types",
          referencesColumn: "id",
        },
        {
          name: "product_size_ranges_pkey",
          type: "PRIMARY KEY",
          column: "id",
          referencesTable: "product_size_ranges",
          referencesColumn: "id",
        },
        {
          name: "product_size_ranges_product_id_fkey",
          type: "FOREIGN KEY",
          column: "product_id",
          referencesTable: "products",
          referencesColumn: "id",
        },
      ],
    },
    {
      table: "products",
      columns: [
        {
          udt: "uuid",
          name: "id",
          default: null,
          dataType: "uuid",
          nullable: false,
          position: 1,
          maxLength: null,
          numericScale: null,
          numericPrecision: null,
        },
        {
          udt: "varchar",
          name: "name",
          default: null,
          dataType: "character varying",
          nullable: false,
          position: 2,
          maxLength: 255,
          numericScale: null,
          numericPrecision: null,
        },
        {
          udt: "text",
          name: "description",
          default: null,
          dataType: "text",
          nullable: true,
          position: 3,
          maxLength: null,
          numericScale: null,
          numericPrecision: null,
        },
        {
          udt: "numeric",
          name: "price",
          default: null,
          dataType: "numeric",
          nullable: false,
          position: 4,
          maxLength: null,
          numericScale: 2,
          numericPrecision: 10,
        },
        {
          udt: "int4",
          name: "stock",
          default: "0",
          dataType: "integer",
          nullable: false,
          position: 5,
          maxLength: null,
          numericScale: 0,
          numericPrecision: 32,
        },
        {
          udt: "uuid",
          name: "brand_id",
          default: null,
          dataType: "uuid",
          nullable: false,
          position: 6,
          maxLength: null,
          numericScale: null,
          numericPrecision: null,
        },
        {
          udt: "uuid",
          name: "sub_category_id",
          default: null,
          dataType: "uuid",
          nullable: false,
          position: 7,
          maxLength: null,
          numericScale: null,
          numericPrecision: null,
        },
        {
          udt: "timestamptz",
          name: "created_at",
          default: null,
          dataType: "timestamp with time zone",
          nullable: false,
          position: 8,
          maxLength: null,
          numericScale: null,
          numericPrecision: null,
        },
        {
          udt: "timestamptz",
          name: "updated_at",
          default: null,
          dataType: "timestamp with time zone",
          nullable: false,
          position: 9,
          maxLength: null,
          numericScale: null,
          numericPrecision: null,
        },
      ],
      indexes: [
        {
          name: "products_pkey",
          definition:
            "CREATE UNIQUE INDEX products_pkey ON public.products USING btree (id)",
        },
      ],
      constraints: [
        {
          name: "2200_16426_1_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "2200_16426_2_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "2200_16426_4_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "2200_16426_5_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "2200_16426_6_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "2200_16426_7_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "2200_16426_8_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "2200_16426_9_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "products_brand_id_fkey",
          type: "FOREIGN KEY",
          column: "brand_id",
          referencesTable: "brands",
          referencesColumn: "id",
        },
        {
          name: "products_pkey",
          type: "PRIMARY KEY",
          column: "id",
          referencesTable: "products",
          referencesColumn: "id",
        },
        {
          name: "products_sub_category_id_fkey",
          type: "FOREIGN KEY",
          column: "sub_category_id",
          referencesTable: "sub_categories",
          referencesColumn: "id",
        },
      ],
    },
    {
      table: "rider_measurements",
      columns: [
        {
          udt: "uuid",
          name: "id",
          default: null,
          dataType: "uuid",
          nullable: false,
          position: 1,
          maxLength: null,
          numericScale: null,
          numericPrecision: null,
        },
        {
          udt: "uuid",
          name: "rider_id",
          default: null,
          dataType: "uuid",
          nullable: false,
          position: 2,
          maxLength: null,
          numericScale: null,
          numericPrecision: null,
        },
        {
          udt: "uuid",
          name: "measurement_type_id",
          default: null,
          dataType: "uuid",
          nullable: false,
          position: 3,
          maxLength: null,
          numericScale: null,
          numericPrecision: null,
        },
        {
          udt: "numeric",
          name: "value",
          default: null,
          dataType: "numeric",
          nullable: false,
          position: 4,
          maxLength: null,
          numericScale: 2,
          numericPrecision: 5,
        },
        {
          udt: "timestamptz",
          name: "measurement_date",
          default: null,
          dataType: "timestamp with time zone",
          nullable: false,
          position: 5,
          maxLength: null,
          numericScale: null,
          numericPrecision: null,
        },
        {
          udt: "timestamptz",
          name: "created_at",
          default: null,
          dataType: "timestamp with time zone",
          nullable: false,
          position: 6,
          maxLength: null,
          numericScale: null,
          numericPrecision: null,
        },
        {
          udt: "timestamptz",
          name: "updated_at",
          default: null,
          dataType: "timestamp with time zone",
          nullable: false,
          position: 7,
          maxLength: null,
          numericScale: null,
          numericPrecision: null,
        },
      ],
      indexes: [
        {
          name: "rider_measurements_pkey",
          definition:
            "CREATE UNIQUE INDEX rider_measurements_pkey ON public.rider_measurements USING btree (id)",
        },
      ],
      constraints: [
        {
          name: "2200_16513_1_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "2200_16513_2_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "2200_16513_3_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "2200_16513_4_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "2200_16513_5_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "2200_16513_6_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "2200_16513_7_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "rider_measurements_measurement_type_id_fkey",
          type: "FOREIGN KEY",
          column: "measurement_type_id",
          referencesTable: "measurement_types",
          referencesColumn: "id",
        },
        {
          name: "rider_measurements_pkey",
          type: "PRIMARY KEY",
          column: "id",
          referencesTable: "rider_measurements",
          referencesColumn: "id",
        },
        {
          name: "rider_measurements_rider_id_fkey",
          type: "FOREIGN KEY",
          column: "rider_id",
          referencesTable: "riders",
          referencesColumn: "id",
        },
      ],
    },
    {
      table: "riders",
      columns: [
        {
          udt: "uuid",
          name: "id",
          default: null,
          dataType: "uuid",
          nullable: false,
          position: 1,
          maxLength: null,
          numericScale: null,
          numericPrecision: null,
        },
        {
          udt: "varchar",
          name: "name",
          default: null,
          dataType: "character varying",
          nullable: false,
          position: 2,
          maxLength: 255,
          numericScale: null,
          numericPrecision: null,
        },
        {
          udt: "varchar",
          name: "last_name",
          default: null,
          dataType: "character varying",
          nullable: false,
          position: 3,
          maxLength: 255,
          numericScale: null,
          numericPrecision: null,
        },
        {
          udt: "timestamptz",
          name: "birth_date",
          default: null,
          dataType: "timestamp with time zone",
          nullable: false,
          position: 4,
          maxLength: null,
          numericScale: null,
          numericPrecision: null,
        },
        {
          udt: "enum_riders_gender",
          name: "gender",
          default: null,
          dataType: "USER-DEFINED",
          nullable: false,
          position: 5,
          maxLength: null,
          numericScale: null,
          numericPrecision: null,
        },
        {
          udt: "varchar",
          name: "email",
          default: null,
          dataType: "character varying",
          nullable: false,
          position: 6,
          maxLength: 255,
          numericScale: null,
          numericPrecision: null,
        },
        {
          udt: "varchar",
          name: "password",
          default: null,
          dataType: "character varying",
          nullable: false,
          position: 7,
          maxLength: 255,
          numericScale: null,
          numericPrecision: null,
        },
        {
          udt: "timestamptz",
          name: "created_at",
          default: null,
          dataType: "timestamp with time zone",
          nullable: false,
          position: 8,
          maxLength: null,
          numericScale: null,
          numericPrecision: null,
        },
        {
          udt: "timestamptz",
          name: "updated_at",
          default: null,
          dataType: "timestamp with time zone",
          nullable: false,
          position: 9,
          maxLength: null,
          numericScale: null,
          numericPrecision: null,
        },
      ],
      indexes: [
        {
          name: "riders_email_key",
          definition:
            "CREATE UNIQUE INDEX riders_email_key ON public.riders USING btree (email)",
        },
        {
          name: "riders_email_key1",
          definition:
            "CREATE UNIQUE INDEX riders_email_key1 ON public.riders USING btree (email)",
        },
        {
          name: "riders_pkey",
          definition:
            "CREATE UNIQUE INDEX riders_pkey ON public.riders USING btree (id)",
        },
      ],
      constraints: [
        {
          name: "2200_16449_1_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "2200_16449_2_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "2200_16449_3_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "2200_16449_4_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "2200_16449_5_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "2200_16449_6_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "2200_16449_7_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "2200_16449_8_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "2200_16449_9_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "riders_email_key",
          type: "UNIQUE",
          column: "email",
          referencesTable: "riders",
          referencesColumn: "email",
        },
        {
          name: "riders_email_key1",
          type: "UNIQUE",
          column: "email",
          referencesTable: "riders",
          referencesColumn: "email",
        },
        {
          name: "riders_pkey",
          type: "PRIMARY KEY",
          column: "id",
          referencesTable: "riders",
          referencesColumn: "id",
        },
      ],
    },
    {
      table: "sub_categories",
      columns: [
        {
          udt: "uuid",
          name: "id",
          default: null,
          dataType: "uuid",
          nullable: false,
          position: 1,
          maxLength: null,
          numericScale: null,
          numericPrecision: null,
        },
        {
          udt: "varchar",
          name: "name",
          default: null,
          dataType: "character varying",
          nullable: false,
          position: 2,
          maxLength: 255,
          numericScale: null,
          numericPrecision: null,
        },
        {
          udt: "uuid",
          name: "category_id",
          default: null,
          dataType: "uuid",
          nullable: false,
          position: 3,
          maxLength: null,
          numericScale: null,
          numericPrecision: null,
        },
        {
          udt: "timestamptz",
          name: "created_at",
          default: null,
          dataType: "timestamp with time zone",
          nullable: false,
          position: 4,
          maxLength: null,
          numericScale: null,
          numericPrecision: null,
        },
        {
          udt: "timestamptz",
          name: "updated_at",
          default: null,
          dataType: "timestamp with time zone",
          nullable: false,
          position: 5,
          maxLength: null,
          numericScale: null,
          numericPrecision: null,
        },
      ],
      indexes: [
        {
          name: "sub_categories_pkey",
          definition:
            "CREATE UNIQUE INDEX sub_categories_pkey ON public.sub_categories USING btree (id)",
        },
      ],
      constraints: [
        {
          name: "2200_16399_1_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "2200_16399_2_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "2200_16399_3_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "2200_16399_4_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "2200_16399_5_not_null",
          type: "CHECK",
          column: null,
          referencesTable: null,
          referencesColumn: null,
        },
        {
          name: "sub_categories_category_id_fkey",
          type: "FOREIGN KEY",
          column: "category_id",
          referencesTable: "categories",
          referencesColumn: "id",
        },
        {
          name: "sub_categories_pkey",
          type: "PRIMARY KEY",
          column: "id",
          referencesTable: "sub_categories",
          referencesColumn: "id",
        },
      ],
    },
  ],
};
